global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    site: ss-control

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "container_blkio.*"
        action: drop

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
